/* RLIB - Convenience library for useful things
 * Copyright (C) 2016  Haakon Sporsheim <haakon.sporsheim@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 * See the COPYING file at the root of the source repository.
 */
#ifndef __R_CRYPTO_ECURVE_H__
#define __R_CRYPTO_ECURVE_H__

#if !defined(__RLIB_H_INCLUDE_GUARD__) && !defined(RLIB_COMPILATION)
#error "#include <rlib.h> only pelase."
#endif

#include <rlib/rtypes.h>
#include <rlib/data/rmpint.h>

R_BEGIN_DECLS

/* Identifiers for the named elliptic curves and TLS / DH groups defined
 * by the IANA registries — the values match the TLS NamedGroup
 * codepoints (RFC 4492, RFC 7027, RFC 7919, TLS 1.3). Not all of these
 * are supported by the math layer; r_ecurve_init returns FALSE for
 * anything outside the prime curves currently shipped. */
typedef enum {
  R_ECURVE_ID_NONE                             = 0,
  R_ECURVE_ID_SECT163K1                        = 0x0001, /* [RFC4492] */
  R_ECURVE_ID_SECT163R1                        = 0x0002, /* [RFC4492] */
  R_ECURVE_ID_SECT163R2                        = 0x0003, /* [RFC4492] */
  R_ECURVE_ID_SECT193R1                        = 0x0004, /* [RFC4492] */
  R_ECURVE_ID_SECT193R2                        = 0x0005, /* [RFC4492] */
  R_ECURVE_ID_SECT233K1                        = 0x0006, /* [RFC4492] */
  R_ECURVE_ID_SECT233R1                        = 0x0007, /* [RFC4492] */
  R_ECURVE_ID_SECT239K1                        = 0x0008, /* [RFC4492] */
  R_ECURVE_ID_SECT283K1                        = 0x0009, /* [RFC4492] */
  R_ECURVE_ID_SECT283R1                        = 0x000a, /* [RFC4492] */
  R_ECURVE_ID_SECT409K1                        = 0x000b, /* [RFC4492] */
  R_ECURVE_ID_SECT409R1                        = 0x000c, /* [RFC4492] */
  R_ECURVE_ID_SECT571K1                        = 0x000d, /* [RFC4492] */
  R_ECURVE_ID_SECT571R1                        = 0x000e, /* [RFC4492] */
  R_ECURVE_ID_SECP160K1                        = 0x000f, /* [RFC4492] */
  R_ECURVE_ID_SECP160R1                        = 0x0010, /* [RFC4492] */
  R_ECURVE_ID_SECP160R2                        = 0x0011, /* [RFC4492] */
  R_ECURVE_ID_SECP192K1                        = 0x0012, /* [RFC4492] */
  R_ECURVE_ID_SECP192R1                        = 0x0013, /* [RFC4492] */
  R_ECURVE_ID_SECP224K1                        = 0x0014, /* [RFC4492] */
  R_ECURVE_ID_SECP224R1                        = 0x0015, /* [RFC4492] */
  R_ECURVE_ID_SECP256K1                        = 0x0016, /* [RFC4492] */
  R_ECURVE_ID_SECP256R1                        = 0x0017, /* [RFC4492] */
  R_ECURVE_ID_SECP384R1                        = 0x0018, /* [RFC4492] */
  R_ECURVE_ID_SECP521R1                        = 0x0019, /* [RFC4492] */
  R_ECURVE_ID_BRAINPOOLP256R1                  = 0x001a, /* [RFC7027] */
  R_ECURVE_ID_BRAINPOOLP348R1                  = 0x001b, /* [RFC7027] */
  R_ECURVE_ID_BRAINPOOLP512R1                  = 0x001c, /* [RFC7027] */
  R_ECURVE_ID_X25519                           = 0x001d, /* [TLS1.3] */
  R_ECURVE_ID_X448                             = 0x001e, /* [TLS1.3] */
  R_ECURVE_ID_FFDHE2048                        = 0x0100, /* [RFC7919] */
  R_ECURVE_ID_FFDHE3072                        = 0x0101, /* [RFC7919] */
  R_ECURVE_ID_FFDHE4096                        = 0x0102, /* [RFC7919] */
  R_ECURVE_ID_FFDHE6144                        = 0x0103, /* [RFC7919] */
  R_ECURVE_ID_FFDHE8192                        = 0x0104, /* [RFC7919] */
  R_ECURVE_ID_ARBITRARY_EXPLICIT_PRIME_CURVES  = 0xff01, /* [RFC4492] */
  R_ECURVE_ID_ARBITRARY_EXPLICIT_CHAR2_CURVES  = 0xff02, /* [RFC4492] */
} REcurveID;

/* Short-Weierstrass affine point. Identity is the algebraic infinity,
 * tracked via a flag rather than a magic coordinate so callers don't
 * have to special-case e.g. (0, 0), which is a valid finite point on
 * many curves. */
typedef struct {
  rmpint x;
  rmpint y;
  rboolean is_infinity;
} REcurveAffinePoint;

/* Per-curve parameters for short-Weierstrass form y^2 = x^3 + ax + b
 * over GF(p), with subgroup of prime order n generated by G.
 *
 * a, b, n, G are stored in normal (non-Montgomery) form so the
 * public point API can keep operating on raw coordinates. The
 * Montgomery setup constants (mont_mp, mont_r_squared) and a
 * pre-converted copy of the a coefficient (mont_a = a * R mod p)
 * are precomputed at r_ecurve_init so the secret-dependent
 * scalar-multiplication ladder can run a constant-time Montgomery
 * variant of the point arithmetic without paying conversion cost
 * per bit. */
typedef struct {
  rmpint p;
  rmpint a;
  rmpint b;
  rmpint n;
  REcurveAffinePoint G;
  rsize coord_bytes;
  rmpint_digit mont_mp;       /* -p^-1 mod 2^digit_bits */
  rmpint mont_r_squared;      /* R^2 mod p */
  rmpint mont_a;              /* a * R mod p - used by the Montgomery dbl */
} REcurve;

R_API void r_ecurve_point_init (REcurveAffinePoint * point);
R_API void r_ecurve_point_clear (REcurveAffinePoint * point);
R_API void r_ecurve_point_set_infinity (REcurveAffinePoint * point);
R_API void r_ecurve_point_copy (REcurveAffinePoint * dst, const REcurveAffinePoint * src);

/* Returns FALSE for unsupported curves (anything other than the prime
 * curves currently shipped). */
R_API rboolean r_ecurve_init (REcurve * curve, REcurveID named);
R_API void r_ecurve_clear (REcurve * curve);

/* Maps an X.509 / SEC 1 elliptic-curve OID to the matching REcurveID
 * enum value. Returns FALSE for OIDs we don't recognise. */
R_API rboolean r_ecurve_id_from_oid (REcurveID * curve,
    rconstpointer oid, rsize oidsize);

R_API rboolean r_ecurve_point_neg (REcurveAffinePoint * out,
    const REcurveAffinePoint * a, const REcurve * curve);
R_API rboolean r_ecurve_point_dbl (REcurveAffinePoint * out,
    const REcurveAffinePoint * a, const REcurve * curve);
R_API rboolean r_ecurve_point_add (REcurveAffinePoint * out,
    const REcurveAffinePoint * a, const REcurveAffinePoint * b,
    const REcurve * curve);
R_API rboolean r_ecurve_point_is_on_curve (const REcurveAffinePoint * point,
    const REcurve * curve);
R_API rboolean r_ecurve_point_scalar_mul (REcurveAffinePoint * out,
    const rmpint * scalar, const REcurveAffinePoint * point,
    const REcurve * curve);

/* Uncompressed SEC 1 encoding: 0x04 || X || Y, padded to coord_bytes.
 * Identity encodes / decodes as a single 0x00 byte. Decoding runs
 * on-curve validation. Compressed (0x02 / 0x03) not yet supported. */
R_API rboolean r_ecurve_point_to_uncompressed (const REcurveAffinePoint * point,
    const REcurve * curve, ruint8 * out, rsize * outsize);
R_API rboolean r_ecurve_point_from_uncompressed (const ruint8 * in,
    rsize insize, const REcurve * curve, REcurveAffinePoint * out);

R_END_DECLS

#endif /* __R_CRYPTO_ECURVE_H__ */
