version: '{build}'

image:
    - Visual Studio 2015
    - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - debug
  - release

install:
  - ps: (new-object net.webclient).DownloadFile("https://www.dropbox.com/s/cyghxjrvgplu7sy/ninja.exe?dl=1", "$env:USERPROFILE\ninja.exe")
  - cmd: set "MESON_PYTHON_PATH=C:\python36-x64"
  - cmd: set "PATH=%USERPROFILE%;%MESON_PYTHON_PATH%\Scripts;%MESON_PYTHON_PATH%;%PATH%"
  - cmd: echo Using Python at %MESON_PYTHON_PATH%
  - cmd: pip install meson

before_build:
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform% )
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform% )

build_script:
  - cmd: echo Building %configuration% on %platform%
  - cmd: meson --backend=ninja --buildtype=%configuration% _build_
  - cmd: ninja -C _build_
  - cmd: 7z a rlib.zip _build_ -xr!*@*

test_script:
  - cmd: ninja -C _build_ test
  - cmd: type C:\projects\rlib\_build_\meson-logs\testlog.txt

artifacts:
  - path: rlib.zip
    name: rlib
