version: '{build}'

image:
    - Visual Studio 2015
    - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - debug
  - release

environment:
  NINJA_DIR: C:\Tools\ninja

cache:
  - C:\Tools\ninja\ninja.exe -> appveyor.yml

install:
  - cmd: if not exist %NINJA_DIR%\ mkdir %NINJA_DIR%
  - cmd: if not exist %NINJA_DIR%\ninja.exe appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip
  - cmd: if not exist %NINJA_DIR%\ninja.exe 7z x ninja-win.zip -o"%NINJA_DIR%"
  - cmd: set "MESON_PYTHON_PATH=C:\python36-x64"
  - cmd: set "PATH=%NINJA_DIR%;%MESON_PYTHON_PATH%\Scripts;%MESON_PYTHON_PATH%;%PATH%"
  - cmd: echo Using Python at %MESON_PYTHON_PATH%
  - cmd: pip install meson

before_build:
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform% )
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform% )

build_script:
  - cmd: echo Building %configuration% on %platform%
  - cmd: meson --backend=ninja --buildtype=%configuration% _build_
  - cmd: ninja -C _build_
  - cmd: 7z a rlib.zip _build_ -xr!*@*

test_script:
  - cmd: meson test -C _build_ --print-errorlogs || type %APPVEYOR_BUILD_FOLDER%\_build_\meson-logs\testlog.txt
  - cmd: if "%configuration%" == "release" ( meson test -C _build_ --benchmark -t 100 --print-errorlogs )
  - type %APPVEYOR_BUILD_FOLDER%\_build_\meson-logs\testlog*.txt

artifacts:
  - path: rlib.zip
    name: rlib
