-
    version: 1.0.{build}
    clone_depth: 15
    environment:
        matrix:
            - VARIANT: debug
              WAFTESTCMD: test
            - VARIANT: release
              WAFTESTCMD: test
            - VARIANT: release
              WAFTESTCMD: bench
    build_script:
        - ps: python waf --variant=${env:VARIANT} configure --msvc_version="msvc 14.0" build
    test_script:
        - ps: python waf --variant=${env:VARIANT} ${env:WAFTESTCMD}
