language: c
dist: trusty
sudo: required
python:
  - 3.5

compiler:
  - clang
  - gcc
os:
  - linux
  - osx
env:
  global:
    - secure: "fKqQXaILVkLVxGKZImTZtCUGr8YXdmNU2VRl+tPBJE866pt1X6FXJ4IVnbE32NTsWiBvkmgy0Y690wF9Lt5L4DatIrINLBTVnHsWjsO8F1kpfTYsK00umXdbj0W0Paba9JH/6erYsEKWrfoR38Hpxt8X+rgZlEO/E+0DDzq8gITdslh3jVp+6wxML5krCQ3KvGQs4KNKHVWhJNVuNYF/DyQmzfBJ98djijL9foC1QrxsuB6KOo93bBiHCYv8Cx0GYFhXFmqDlTqeiioBvu0NMnNBlMm9HXRN6H46RW6L+BnV8trYtuFppXKEquihoGs2wN27FNFs5+N+b/tsSc8lhgEMJcOaDIMPvBEHkcLjpiVDyV9tbsqW9EAWe6vhjlF5CKYxNiEpI1rSSD0dzLdeRV7nDRa1YZDr+v9AbBkrBZSLnQxQBx67B9paNDl+rAOHpl2GbOJaZ7WSdABZWH26LDv9Tav1mIKkKS2McdnYkWajyJH+IIlgtdwATXYlFtwCj51QBLgyd20YuLOFu7oso2bpXJ9pBg1nqCOFCpSfOxhAhEDR2Hv9PCkCJWch20+fLHUqwG62dUHkpsoPKh3Vlxs9bQ1MU5XdkAtIbnbVlKgdcP7jL0GYGZG+WR3s8L2cbToNYtlM2ii1ZvYQe5UCt+PBRqqa9kTBOLzHi64Nd/4="
  matrix:
    - BLDTYPE=debug   TESTTYPE=valgrind
    - BLDTYPE=release TESTTYPE=valgrind
    - BLDTYPE=debug   TESTTYPE=normal
    - BLDTYPE=release TESTTYPE=normal
    - BLDTYPE=release TESTTYPE=bench

matrix:
  exclude:
    - os: osx
      env: BLDTYPE=debug   TESTTYPE=valgrind
    - os: osx
      env: BLDTYPE=release TESTTYPE=valgrind

before_install:
  - test "$TRAVIS_BRANCH" != "coverity_scan" || test "$TRAVIS_OS_NAME" = "linux" -a "$BLDTYPE" = "release" -a "$CC" = "gcc" -a -z "$VG_OPT" || exit 0
  - export PATH="`pwd`/build:${PATH}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install python3 ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then pyenv global system 3.5; fi
  - pip3 install meson

script:
  - test "$TRAVIS_BRANCH" != "coverity_scan" || exit 0
  - meson --buildtype=${BLDTYPE} build
  - ninja -C build
  - if [[ "$TESTTYPE" == "normal" ]]; then mesontest -C build --print-errorlogs; fi
  - if [[ "$TESTTYPE" == "valgrind" ]]; then RNOTIMEOUT=1 mesontest -C build --print-errorlogs -t 100 --wrap='valgrind -q --error-exitcode=42 --tool=memcheck --leak-check=full'; fi
  - if [[ "$TESTTYPE" == "bench" ]]; then mesontest -C build --benchmark -t 100 --print-errorlogs; fi

after_failure:
  - if [[ -e $TRAVIS_BUILD_DIR/build/meson-logs/testlog.txt ]]; then cat $TRAVIS_BUILD_DIR/build/meson-logs/testlog.txt; fi

addons:
  apt:
    packages:
      - valgrind
  coverity_scan:
    project:
      name: "ieei/rlib"
      description: "Build submitted via Travis CI"
    notification_email: haakon.sporsheim@gmail.com
    build_command_prepend: "python waf distclean configure"
    build_command:   "python waf build"
    branch_pattern: coverity_scan

