/* RLIB - Convenience library for useful things
 * Copyright (C) 2026  Haakon Sporsheim <haakon.sporsheim@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 * See the COPYING file at the root of the source repository.
 */

/* UCD-backed codepoint property accessors. The lookup table is
 * generated by tools/gen_unicode_props.py from the vendored
 * UnicodeData.txt + PropList.txt under data/ucd/<version>/ and
 * included verbatim from runicode-props.inc.
 *
 * The packing rationale and full set of size numbers live in the
 * generator's output header (search the .inc for "Sizes:"). */

#include "config.h"
#include <rlib/charset/runicode.h>

#include "runicode-props.inc"

/* Fetch the packed property byte for a codepoint. Out-of-range
 * codepoints (>= 0x110000) and the high tail of the codepoint
 * space land on a stage-2 page filled with Cn entries by the
 * generator's full-range scan. */
static inline ruint8
r_unicode_props_byte (runichar4 uc)
{
  if (uc >= 0x110000u)
    return R_UNICODE_GC_CN;
  return g__unicode_props_pages[g__unicode_props_stage1[uc >> 8]][uc & 0xff];
}

static inline ruint8
r_unicode_props_gc (runichar4 uc)
{
  return r_unicode_props_byte (uc) & R_UNICODE_PROPS_GC_MASK;
}

/* Category membership predicates built on a 30-bit mask over the
 * GC enumeration. The constants below pack the General_Category
 * indices the generator emits (R_UNICODE_GC_LU == 0 etc.) into a
 * single ruint32; testing membership is one shift + AND. */
#define GC_BIT(gc)         (1u << R_UNICODE_GC_ ## gc)

#define GC_MASK_LETTER     (GC_BIT (LU) | GC_BIT (LL) | GC_BIT (LT) | \
                            GC_BIT (LM) | GC_BIT (LO))
#define GC_MASK_DIGIT      (GC_BIT (ND))
#define GC_MASK_ALNUM      (GC_MASK_LETTER | GC_MASK_DIGIT)
#define GC_MASK_CONTROL    (GC_BIT (CC))
#define GC_MASK_NONPRINT   (GC_BIT (CC) | GC_BIT (CF) | GC_BIT (CS) | \
                            GC_BIT (CO) | GC_BIT (CN))
#define GC_MASK_PUNCT      (GC_BIT (PC) | GC_BIT (PD) | GC_BIT (PS) | \
                            GC_BIT (PE) | GC_BIT (PI) | GC_BIT (PF) | \
                            GC_BIT (PO))
#define GC_MASK_MARK       (GC_BIT (MN) | GC_BIT (MC) | GC_BIT (ME))
#define GC_MASK_SYMBOL     (GC_BIT (SM) | GC_BIT (SC) | GC_BIT (SK) | \
                            GC_BIT (SO))

rboolean
r_unichar_is_letter (runichar4 uc)
{
  return ((1u << r_unicode_props_gc (uc)) & GC_MASK_LETTER) != 0u;
}

rboolean
r_unichar_is_digit (runichar4 uc)
{
  return ((1u << r_unicode_props_gc (uc)) & GC_MASK_DIGIT) != 0u;
}

rboolean
r_unichar_is_alnum (runichar4 uc)
{
  return ((1u << r_unicode_props_gc (uc)) & GC_MASK_ALNUM) != 0u;
}

rboolean
r_unichar_is_space (runichar4 uc)
{
  if (uc >= 0x110000u) return FALSE;
  return (r_unicode_props_byte (uc) & R_UNICODE_PROPS_WHITE_SPACE) != 0u;
}

rboolean
r_unichar_is_control (runichar4 uc)
{
  return ((1u << r_unicode_props_gc (uc)) & GC_MASK_CONTROL) != 0u;
}

rboolean
r_unichar_is_print (runichar4 uc)
{
  /* Unicode Standard recommendation: printable = NOT in
   * {Cc, Cf, Cs, Co, Cn}. Out-of-range codepoints fall into Cn
   * via r_unicode_props_gc and return FALSE accordingly. */
  return ((1u << r_unicode_props_gc (uc)) & GC_MASK_NONPRINT) == 0u;
}

rboolean
r_unichar_is_punct (runichar4 uc)
{
  return ((1u << r_unicode_props_gc (uc)) & GC_MASK_PUNCT) != 0u;
}

rboolean
r_unichar_is_mark (runichar4 uc)
{
  return ((1u << r_unicode_props_gc (uc)) & GC_MASK_MARK) != 0u;
}

rboolean
r_unichar_is_symbol (runichar4 uc)
{
  return ((1u << r_unicode_props_gc (uc)) & GC_MASK_SYMBOL) != 0u;
}

/* Sparse binary search on the sorted simple-case-mapping table.
 * Codepoints with no entry get the identity mapping per UAX #44. */
static const RUnicodePropsCaseEntry *
r_unicode_props_case_lookup (runichar4 uc)
{
  rsize lo = 0;
  rsize hi = R_N_ELEMENTS (g__unicode_props_cases);

  while (lo < hi) {
    rsize mid = lo + (hi - lo) / 2;
    if (g__unicode_props_cases[mid].cp < uc)
      lo = mid + 1;
    else if (g__unicode_props_cases[mid].cp > uc)
      hi = mid;
    else
      return &g__unicode_props_cases[mid];
  }
  return NULL;
}

runichar4
r_unichar_to_upper (runichar4 uc)
{
  const RUnicodePropsCaseEntry * e = r_unicode_props_case_lookup (uc);
  return (e != NULL) ? (runichar4)((rint32)uc + e->upper_delta) : uc;
}

runichar4
r_unichar_to_lower (runichar4 uc)
{
  const RUnicodePropsCaseEntry * e = r_unicode_props_case_lookup (uc);
  return (e != NULL) ? (runichar4)((rint32)uc + e->lower_delta) : uc;
}

runichar4
r_unichar_to_title (runichar4 uc)
{
  const RUnicodePropsCaseEntry * e = r_unicode_props_case_lookup (uc);
  return (e != NULL) ? (runichar4)((rint32)uc + e->title_delta) : uc;
}
