#!/usr/bin/env python
#encoding: utf-8

def build(bld):
    excl = []

    if bld.env.BUILD_BIN:
        bld.program(features='bench', source=bld.path.ant_glob('*.c', excl=excl),
                target='rlibbench', use=bld.env.RLIB_INTERNAL_USE, includes='..')

